### ISSUE TITLE
hydroflow-template panics

### ISSUE THREAD

**Issue by jhellerstein** [hydro-project/hydroflow#693]
```
(base) sledgehammer]> RUST_BACKTRACE=1 cargo run -- --role server
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
     Running `target/debug/hydroflow-template --role server`
Listening on 127.0.0.1:65276
Server live!
thread 'main' panicked at '`spawn_local` called from outside of a `task::LocalSet`', /Users/jmh/.cargo/git/checkouts/hydroflow-bd9de84a73a76f97/8a5b487/hydroflow/src/scheduled/context.rs:147:19
stack backtrace:
   0: rust_begin_unwind
             at /rustc/77f4f828a2f19854fcbcdf69babe7d0ac1c92852/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/77f4f828a2f19854fcbcdf69babe7d0ac1c92852/library/core/src/panicking.rs:67:14
   2: tokio::task::local::spawn_local_inner
             at /Users/jmh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.1/src/task/local.rs:345:21
   3: tokio::task::local::spawn_local
             at /Users/jmh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.1/src/task/local.rs:335:9
   4: hydroflow::scheduled::context::Context::spawn_task
             at /Users/jmh/.cargo/git/checkouts/hydroflow-bd9de84a73a76f97/8a5b487/hydroflow/src/scheduled/context.rs:147:19
   5: hydroflow::scheduled::graph::Hydroflow::spawn_task
             at /Users/jmh/.cargo/git/checkouts/hydroflow-bd9de84a73a76f97/8a5b487/hydroflow/src/scheduled/graph.rs:563:9
   6: hydroflow_template::server::run_server::{{closure}}
             at ./src/server.rs:12:31
   7: hydroflow_template::main::{{closure}}
             at ./src/main.rs:54:49
   8: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /Users/jmh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.1/src/runtime/park.rs:283:63
   9: tokio::runtime::coop::with_budget
             at /Users/jmh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.1/src/runtime/coop.rs:107:5
  10: tokio::runtime::coop::budget
             at /Users/jmh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.1/src/runtime/coop.rs:73:5
  11: tokio::runtime::park::CachedParkThread::block_on
             at /Users/jmh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.1/src/runtime/park.rs:283:31
  12: tokio::runtime::context::BlockingRegionGuard::block_on
             at /Users/jmh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.1/src/runtime/context.rs:315:13
  13: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /Users/jmh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.1/src/runtime/scheduler/multi_thread/mod.rs:66:9
  14: tokio::runtime::runtime::Runtime::block_on
             at /Users/jmh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.1/src/runtime/runtime.rs:304:45
  15: hydroflow_template::main
             at ./src/main.rs:52:5
  16: core::ops::function::FnOnce::call_once
             at /rustc/77f4f828a2f19854fcbcdf69babe7d0ac1c92852/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
(base) sledgehammer]>  
```

**Comment by MingweiSamuel** [comment]
@zzlk

**Comment by zzlk** [comment]
likely just needs hydroflow::main
